//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace operation_by_territory
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClarkAddress
    {
        public decimal LON { get; set; }
        public decimal LAT { get; set; }
        public string NUMBER { get; set; }
        public string STREET { get; set; }
        public string UNIT { get; set; }
        public string CITY { get; set; }
        public string DISTRICT { get; set; }
        public string REGION { get; set; }
        public string POSTCODE { get; set; }
        public string ID { get; set; }
        public string HASH { get; set; }
    }
}
