//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace operation_by_territory
{
    using System;
    using System.Collections.Generic;
    
    public partial class TerritoryPoint
    {
        public int PointId { get; set; }
        public string Name { get; set; }
        public string TerritoryType { get; set; }
        public int TerritoryNumber { get; set; }
        public decimal Lat { get; set; }
        public decimal Long { get; set; }
    }
}
